Water quality
digitalearthafrica/deafrica-sandbox-notebooks pull request #181
Opened 2021-02-04 17:45 UTC by nanaboamah89

### Proposed changes
calc_geomedian function was replaced with xr_geomedian.
Cell 1 and 8 was updated to use the xr_geomedian function.

### Closes issues (optional)
- Closes Issue #000
- Closes Issue #000

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell and re-use tags if possible
- [x ] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

2021-02-04 22:59 UTC, cbur24 requested changes
Thanks for spotting this @nanaboamah89.  Changes to the notebook look good. However, before I can approve the merge you need to remove the other 7 files that are being tracked by this PR.

2021-02-05 21:26 UTC, nanaboamah89 commented
Hi @cbur24 , Kindly check if all the files have been removed.

2021-02-08 05:38 UTC, cbur24 commented
@nanaboamah89 `Real_world_examples/Urban_change_detection.ipynb` is still included in the PR. You can see which files are included in the PR by clicking on the `Files Changed` tab above

2021-02-09 22:23 UTC, cbur24 approved these changes

2021-02-09 22:23 UTC, merged